[project]
name = "imagewriter"
version = "1.0.0"
authors = [
  {name = "Josh Holbrook", email = "josh.holbrook@gmail.com"}
]
description = "Print server and utilities for the ImageWriter II color dot matrix printer"
readme = "README.md"
keywords = []
license = "MPL-2.0"
classifiers = [
  "Programming Language :: Python",
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.15",
  "Topic :: System :: Hardware",
  "Topic :: System :: Hardware :: Hardware Drivers",
  "Topic :: Terminals :: Serial",
]

requires-python = ">=3.15"
dependencies = [
  "aiodns",
  "aiohttp",
  "dependency-injector",
  "ipywidgets",
  "pyserial",
]

[dependency-groups]
dev = [
  "black[jupyter]",
  "flake8",
  "flake8-black",
  "isort",
  "mypy",
  "pytest",
  "pytest-asyncio",
  "pytest-gak",
  "jupyterlab",
  "mkdocs",
  "mkdocs-include-markdown-plugin",
  "mkdocstrings[python]",
  "syrupy",
  "types-pyserial",
  "validate-pyproject[all]",
]

[build-system]
requires = ["uv_build >= 0.12.5, < 0.13"]
build-backend = "uv_build"

[tool.uv]
package = true

[tool.black]
target-version = ["py315"]

[tool.isort]
profile = "appnexus"
known_application = "imagewriter"

[tool.pytest.ini_options]
addopts = "--verbose -s"
testpaths = [ "tests" ]

[tool.pyright]
include = ["src", "tests"]
