from typing import List

from imagewriter.encoding.attributes import (
    boldface,
    double_width,
    half_height,
    PRINT_SLASHED_ZERO,
    PRINT_UNSLASHED_ZERO,
    START_BOLDFACE,
    START_DOUBLE_WIDTH,
    START_HALF_HEIGHT,
    START_SUBSCRIPT,
    START_SUPERSCRIPT,
    START_UNDERLINE,
    STOP_BOLDFACE,
    STOP_DOUBLE_WIDTH,
    STOP_HALF_HEIGHT,
    STOP_SUBSCRIPT,
    STOP_SUPERSCRIPT,
    STOP_UNDERLINE,
    underline,
)
from imagewriter.encoding.base import Bytes, Command, ctrl, Ctrl, esc, Esc
from imagewriter.encoding.boundaries import SetLeftMargin, SetPageLength
from imagewriter.encoding.cancel import CANCEL_CURRENT_LINE
from imagewriter.encoding.character import CharacterEncoder, Text
from imagewriter.encoding.character.custom import (
    BOTTOM_WIRES,
    character_data,
    CustomCharacter,
    TOP_WIRES,
)
from imagewriter.encoding.color import set_color
from imagewriter.encoding.graphics import (
    PrintGraphicsData,
    SET_GRAPHICS_DISTANCE_BETWEEN_LINES,
)
from imagewriter.encoding.motion import (
    BACKSPACE,
    ClearAllTabs,
    ClearManyTabs,
    CR,
    LF,
    LineFeed,
    LineFeedForward,
    LineFeedReverse,
    PlaceExactPrintHeadPosition,
    reset_tabs,
    SET_TOP_OF_FORM,
    SetAutoLFAfterCR,
    SetCarriageReturnInsertion,
    SetDistanceBetweenLines,
    SetLFWhenLineFull,
    SetLinesPerInch,
    SetManyTabs,
    SetOneTab,
    SetPerforationSkip,
    SetUnidirectionalPrinting,
    TAB,
    to_tab_stops,
)
from imagewriter.encoding.paper import SetPaperOutSensor
from imagewriter.encoding.pitch import InsertSpaces, SetPitch, SetSpacing
from imagewriter.encoding.print import SetPrintCommands
from imagewriter.encoding.quality import SetQuality
from imagewriter.encoding.repeat import repeat
from imagewriter.encoding.reset import RESET
from imagewriter.encoding.select import DESELECT, SELECT, SetSoftwareSelectResponse
from imagewriter.encoding.settings import apply_settings
from imagewriter.encoding.switch import CloseSoftwareSwitches, OpenSoftwareSwitches

__all__: List[str] = [
    "boldface",
    "double_width",
    "half_height",
    "PRINT_SLASHED_ZERO",
    "PRINT_UNSLASHED_ZERO",
    "START_DOUBLE_WIDTH",
    "STOP_DOUBLE_WIDTH",
    "START_UNDERLINE",
    "STOP_UNDERLINE",
    "START_BOLDFACE",
    "STOP_BOLDFACE",
    "START_HALF_HEIGHT",
    "STOP_HALF_HEIGHT",
    "START_SUPERSCRIPT",
    "STOP_SUPERSCRIPT",
    "START_SUBSCRIPT",
    "STOP_SUBSCRIPT",
    "underline",
    "Bytes",
    "ctrl",
    "Ctrl",
    "esc",
    "Esc",
    "Command",
    "SetLeftMargin",
    "SetPageLength",
    "CANCEL_CURRENT_LINE",
    "CharacterEncoder",
    "Text",
    "BOTTOM_WIRES",
    "character_data",
    "CustomCharacter",
    "TOP_WIRES",
    "set_color",
    "PrintGraphicsData",
    "SET_GRAPHICS_DISTANCE_BETWEEN_LINES",
    "BACKSPACE",
    "ClearAllTabs",
    "ClearManyTabs",
    "CR",
    "LF",
    "LineFeed",
    "LineFeedForward",
    "LineFeedReverse",
    "PlaceExactPrintHeadPosition",
    "reset_tabs",
    "SET_TOP_OF_FORM",
    "SetAutoLFAfterCR",
    "SetCarriageReturnInsertion",
    "SetDistanceBetweenLines",
    "SetLFWhenLineFull",
    "SetLinesPerInch",
    "SetManyTabs",
    "SetOneTab",
    "SetPerforationSkip",
    "SetUnidirectionalPrinting",
    "TAB",
    "to_tab_stops",
    "SetPaperOutSensor",
    "InsertSpaces",
    "SetPitch",
    "SetSpacing",
    "SetPrintCommands",
    "SetQuality",
    "repeat",
    "RESET",
    "DESELECT",
    "SELECT",
    "apply_settings",
    "SetSoftwareSelectResponse",
    "CloseSoftwareSwitches",
    "OpenSoftwareSwitches",
]
