from typing import List

from imagewriter.encoding.attributes import (
    boldface,
    double_width,
    half_height,
    PRINT_SLASHED_ZERO,
    PRINT_UNSLASHED_ZERO,
    START_BOLDFACE,
    START_DOUBLE_WIDTH,
    START_HALF_HEIGHT,
    START_SUBSCRIPT,
    START_SUPERSCRIPT,
    START_UNDERLINE,
    STOP_BOLDFACE,
    STOP_DOUBLE_WIDTH,
    STOP_HALF_HEIGHT,
    STOP_SUBSCRIPT,
    STOP_SUPERSCRIPT,
    STOP_UNDERLINE,
    underline,
)
from imagewriter.encoding.base import (
    Bytes,
    Command,
    ctrl,
    Ctrl,
    esc,
    Esc,
    InvalidControlCharacterError,
    LengthError,
    Print,
    Space,
)
from imagewriter.encoding.boundaries import SetLeftMargin, SetPageLength
from imagewriter.encoding.cancel import CANCEL_CURRENT_LINE
from imagewriter.encoding.character import (
    BOTTOM_WIRES,
    CharacterEncoder,
    DISABLE_MODE,
    DisableMode,
    ENABLE_MOUSE_TEXT_MAPPING_MODE,
    EnableCustomCharacterMode,
    EnableMouseTextMappingMode,
    LoadCustomCharacters,
    SetMaxCustomCharacterWidth,
    TOP_WIRES,
)
from imagewriter.encoding.color import SetColor
from imagewriter.encoding.graphics import (
    PrintGraphicsData,
    SET_GRAPHICS_DISTANCE_BETWEEN_LINES,
)
from imagewriter.encoding.language import set_language
from imagewriter.encoding.motion import (
    BACKSPACE,
    Backspace,
    BackspaceLengthError,
    CarriageReturn,
    CarriageReturnLengthError,
    ClearAllTabs,
    ClearManyTabs,
    CR,
    cr_lf,
    CRLF,
    FF,
    LF,
    LineFeed,
    LineFeedForward,
    LineFeedLengthError,
    LineFeedReverse,
    PlaceExactPrintHeadPosition,
    reset_tabs,
    SET_TOP_OF_FORM,
    SetAutoLFAfterCR,
    SetCRInsertion,
    SetDistanceBetweenLines,
    SetLFWhenLineFull,
    SetLinesPerInch,
    SetManyTabs,
    SetOneTab,
    SetPerforationSkip,
    SetTopOfForm,
    SetUnidirectionalPrinting,
    TAB,
    TabLengthError,
    to_tab_stops,
)
from imagewriter.encoding.paper import SetPaperOutSensor
from imagewriter.encoding.pitch import InsertSpaces, SetPitch, SetSpacing
from imagewriter.encoding.print import SetPrintCommands
from imagewriter.encoding.quality import SetQuality
from imagewriter.encoding.repeat import repeat
from imagewriter.encoding.reset import RESET
from imagewriter.encoding.select import DESELECT, SELECT, SetSoftwareSelectResponse
from imagewriter.encoding.settings import apply_settings
from imagewriter.encoding.switch import CloseSoftwareSwitches, OpenSoftwareSwitches

__all__: List[str] = [
    "boldface",
    "double_width",
    "half_height",
    "PRINT_SLASHED_ZERO",
    "PRINT_UNSLASHED_ZERO",
    "START_DOUBLE_WIDTH",
    "STOP_DOUBLE_WIDTH",
    "START_UNDERLINE",
    "STOP_UNDERLINE",
    "START_BOLDFACE",
    "STOP_BOLDFACE",
    "START_HALF_HEIGHT",
    "STOP_HALF_HEIGHT",
    "START_SUPERSCRIPT",
    "STOP_SUPERSCRIPT",
    "START_SUBSCRIPT",
    "STOP_SUBSCRIPT",
    "underline",
    "Bytes",
    "ctrl",
    "Ctrl",
    "esc",
    "Esc",
    "InvalidControlCharacterError",
    "LengthError",
    "Print",
    "Space",
    "Command",
    "SetLeftMargin",
    "SetPageLength",
    "CANCEL_CURRENT_LINE",
    "SetMaxCustomCharacterWidth",
    "LoadCustomCharacters",
    "DisableMode",
    "DISABLE_MODE",
    "EnableCustomCharacterMode",
    "EnableMouseTextMappingMode",
    "ENABLE_MOUSE_TEXT_MAPPING_MODE",
    "CharacterEncoder",
    "TOP_WIRES",
    "BOTTOM_WIRES",
    "SetColor",
    "PrintGraphicsData",
    "SET_GRAPHICS_DISTANCE_BETWEEN_LINES",
    "set_language",
    "BACKSPACE",
    "Backspace",
    "BackspaceLengthError",
    "CarriageReturn",
    "CarriageReturnLengthError",
    "ClearAllTabs",
    "ClearManyTabs",
    "CR",
    "CRLF",
    "cr_lf",
    "FF",
    "LF",
    "LineFeed",
    "LineFeedForward",
    "LineFeedLengthError",
    "LineFeedReverse",
    "PlaceExactPrintHeadPosition",
    "reset_tabs",
    "SetTopOfForm",
    "SET_TOP_OF_FORM",
    "SetAutoLFAfterCR",
    "SetCRInsertion",
    "SetDistanceBetweenLines",
    "SetLFWhenLineFull",
    "SetLinesPerInch",
    "SetManyTabs",
    "SetOneTab",
    "SetPerforationSkip",
    "SetUnidirectionalPrinting",
    "TAB",
    "TabLengthError",
    "to_tab_stops",
    "SetPaperOutSensor",
    "InsertSpaces",
    "SetPitch",
    "SetSpacing",
    "SetPrintCommands",
    "SetQuality",
    "repeat",
    "RESET",
    "DESELECT",
    "SELECT",
    "apply_settings",
    "SetSoftwareSelectResponse",
    "CloseSoftwareSwitches",
    "OpenSoftwareSwitches",
]
