from typing import Literal

Format = (
    Literal["biblatex"]
    | Literal["bibtex"]
    | Literal["bits"]
    | Literal["commonmark"]
    | Literal["commonmark_x"]
    | Literal["creole"]
    | Literal["csljson"]
    | Literal["csv"]
    | Literal["djot"]
    | Literal["docbook"]
    | Literal["docx"]
    | Literal["dokuwiki"]
    | Literal["endnotexml"]
    | Literal["epub"]
    | Literal["fb2"]
    | Literal["gfm"]
    | Literal["haddock"]
    | Literal["html"]
    | Literal["ipynb"]
    | Literal["jats"]
    | Literal["jira"]
    | Literal["json"]
    | Literal["latex"]
    | Literal["man"]
    | Literal["markdown"]
    | Literal["markdown_github"]
    | Literal["markdown_mmd"]
    | Literal["markdown_phpextra"]
    | Literal["markdown_strict"]
    | Literal["mdoc"]
    | Literal["mediawiki"]
    | Literal["muse"]
    | Literal["native"]
    | Literal["odt"]
    | Literal["opml"]
    | Literal["org"]
    | Literal["pod"]
    | Literal["ris"]
    | Literal["rst"]
    | Literal["rtf"]
    | Literal["t2t"]
    | Literal["textile"]
    | Literal["tikiwiki"]
    | Literal["tsv"]
    | Literal["twiki"]
    | Literal["typst"]
    | Literal["vimwiki"]
    | Literal["xml"]
)
