from typing import List

import pytest

from imagewriter.character import CustomCharacter, CustomCharacterData
from imagewriter.color import Color
from imagewriter.encoding import (
    BACKSPACE,
    Bytes,
    CANCEL_CURRENT_LINE,
    CLEAR_ALL_TABS,
    ClearManyTabs,
    CloseSoftwareSwitches,
    Command,
    CR,
    Ctrl,
    DESELECT,
    DISABLE_MODE,
    ENABLE_MOUSE_TEXT_MAPPING_MODE,
    EnableCustomCharacterMode,
    Esc,
    FF,
    InsertSpaces,
    LF,
    LINE_FEED_FORWARD,
    LINE_FEED_REVERSE,
    LineFeed,
    LoadCustomCharacters,
    OpenSoftwareSwitches,
    Print,
    PRINT_SLASHED_ZERO,
    PRINT_UNSLASHED_ZERO,
    PrintGraphicsData,
    REQUEST_SELF_IDENTIFY,
    RESET,
    SELECT,
    set_language,
    SET_TOP_OF_FORM,
    SetAutoLFAfterCR,
    SetColor,
    SetCRInsertion,
    SetDistanceBetweenLines,
    SetLeftMargin,
    SetLFWhenLineFull,
    SetLinesPerInch,
    SetManyTabs,
    SetMaxCustomCharacterWidth,
    SetOneTab,
    SetPageLength,
    SetPaperOutSensor,
    SetPerforationSkip,
    SetPitch,
    SetPrintCommands,
    SetQuality,
    SetSoftwareSelectResponse,
    SetSoftwareSwitches,
    SetSpacing,
    SetUnidirectionalPrinting,
    Space,
    START_BOLDFACE,
    START_DOUBLE_WIDTH,
    START_HALF_HEIGHT,
    START_SUBSCRIPT,
    START_SUPERSCRIPT,
    START_UNDERLINE,
    STOP_BOLDFACE,
    STOP_DOUBLE_WIDTH,
    STOP_HALF_HEIGHT,
    STOP_SUBSCRIPT,
    STOP_SUPERSCRIPT,
    STOP_UNDERLINE,
    TAB,
)
from imagewriter.language import Language
from imagewriter.pitch import Pitch
from imagewriter.print import PrintCommands
from imagewriter.quality import Quality
from imagewriter.switch import SoftwareSwitch
from imagewriter.units import Inch

COMMANDS: List[Command] = [
    BACKSPACE,
    Bytes(b"hello"),
    CANCEL_CURRENT_LINE,
    CLEAR_ALL_TABS,
    ClearManyTabs([4, 8, 12]),
    CloseSoftwareSwitches({SoftwareSwitch.LANGUAGE_1, SoftwareSwitch.LANGUAGE_2}),
    CR,
    Ctrl("Q"),
    DESELECT,
    DISABLE_MODE,
    ENABLE_MOUSE_TEXT_MAPPING_MODE,
    EnableCustomCharacterMode(True),
    EnableCustomCharacterMode(False),
    Esc("x"),
    FF,
    # TODO: Should this throw on non-proportional fonts?
    InsertSpaces(Pitch.ELITE_PROPORTIONAL, 2),
    LF,
    LINE_FEED_FORWARD,
    LINE_FEED_REVERSE,
    LineFeed(2),
    LoadCustomCharacters([CustomCharacterData(CustomCharacter(ord("a")), b"1234")]),
    OpenSoftwareSwitches({SoftwareSwitch.LANGUAGE_1, SoftwareSwitch.LANGUAGE_2}),
    Print(b"hello"),
    PRINT_SLASHED_ZERO,
    PRINT_UNSLASHED_ZERO,
    PrintGraphicsData(b"1234"),
    REQUEST_SELF_IDENTIFY,
    RESET,
    SELECT,
    SET_TOP_OF_FORM,
    SetAutoLFAfterCR(True),
    SetAutoLFAfterCR(False),
    SetColor(Color.BLACK),
    SetCRInsertion(True),
    SetCRInsertion(False),
    SetDistanceBetweenLines(6),
    SetLeftMargin(12, Pitch.ELITE),
    SetLeftMargin(Inch(1), Pitch.ELITE),
    *set_language(Language.BRITISH),
    SetLFWhenLineFull(True),
    SetLFWhenLineFull(False),
    SetLinesPerInch(6),
    SetLinesPerInch(8),
    SetManyTabs([4, 8, 12]),
    SetMaxCustomCharacterWidth(8),
    SetMaxCustomCharacterWidth(16),
    SetOneTab(16),
    SetPageLength(12),
    SetPageLength(Inch(11)),
    SetPaperOutSensor(True),
    SetPaperOutSensor(False),
    SetPerforationSkip(True),
    SetPerforationSkip(False),
    SetPitch(Pitch.ELITE),
    SetPrintCommands(PrintCommands.CR_LF_AND_FF),
    SetPrintCommands(PrintCommands.CR_ONLY),
    SetQuality(Quality.NEAR_LETTER_QUALITY),
    SetSoftwareSelectResponse(True),
    SetSoftwareSelectResponse(False),
    SetSoftwareSwitches(True, {SoftwareSwitch.LANGUAGE_1, SoftwareSwitch.LANGUAGE_2}),
    SetSoftwareSwitches(False, {SoftwareSwitch.LANGUAGE_1, SoftwareSwitch.LANGUAGE_2}),
    # TODO: Should this throw on non-proportional fonts?
    SetSpacing(Pitch.ELITE_PROPORTIONAL, 2),
    SetUnidirectionalPrinting(True),
    SetUnidirectionalPrinting(False),
    Space(),
    START_BOLDFACE,
    START_DOUBLE_WIDTH,
    START_HALF_HEIGHT,
    START_SUBSCRIPT,
    START_SUPERSCRIPT,
    START_UNDERLINE,
    STOP_BOLDFACE,
    STOP_DOUBLE_WIDTH,
    STOP_HALF_HEIGHT,
    STOP_SUBSCRIPT,
    STOP_SUPERSCRIPT,
    STOP_UNDERLINE,
    TAB,
]


@pytest.mark.parametrize("command", COMMANDS)
def test_bytes_command(command, snapshot) -> None:
    assert bytes(command) == snapshot


@pytest.mark.parametrize("command", COMMANDS)
def test_repr_command(command, snapshot) -> None:
    assert repr(command) == snapshot
